### ISSUE TITLE
more arguments ??

### ISSUE THREAD

**Issue by baolinliu** [dmakian/feudal_networks#1]
test_init (tests.test_policies.test_lstm_policy.TestLSTMPolicy) ... ERROR

======================================================================
ERROR: test_intrinsic_reward_and_gsum_calculation (tests.test_policies.test_feudal_batch_processor.TestFeudalBatchProcessor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/user/Desktop/feudal_networks/tests/test_policies/test_feudal_batch_processor.py", line 154, in test_intrinsic_reward_and_gsum_calculation
    b = Batch(obs, a, returns, terminal, s, g, features)
TypeError: __new__() takes exactly 7 arguments (8 given)

Not sure why theres more arguments than what it can take.

**Comment by davidhershey** [comment]
The code is still in development, we'll update the readme when everything is working!

**Comment by baolinliu** [comment]
Thanks, looking forward to the full working code.
